# Generated by Django 5.0.3 on 2024-04-06 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0009_alter_subject_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendence',
            name='subject_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='sms.subject'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Attendence_Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendence_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.attendence')),
                ('student_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='sms.subject')),
            ],
        ),
    ]
