# Generated by Django 5.0.3 on 2024-04-06 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0010_attendence_subject_id_attendence_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence_report',
            name='student_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='sms.student'),
        ),
    ]
