# Generated by Django 5.0.3 on 2024-04-06 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0015_remove_subject_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence_report',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sms.student'),
        ),
    ]
