# Generated by Django 5.0.3 on 2024-04-06 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0016_alter_attendence_report_student_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendence_report',
            name='updated_at',
        ),
    ]
