# Generated by Django 5.0.3 on 2024-04-06 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0017_remove_attendence_report_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendence_report',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
