# Generated by Django 5.0.4 on 2024-04-06 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0018_attendence_report_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='staff',
            field=models.ForeignKey(default='Default Staff', on_delete=django.db.models.deletion.CASCADE, to='sms.staff'),
        ),
    ]
