# Generated by Django 5.1 on 2024-11-01 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0020_alter_subject_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='staff',
        ),
    ]
