# Generated by Django 5.1 on 2024-12-01 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0022_staff_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='rollno',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
