# Generated by Django 5.1 on 2025-01-08 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0023_student_rollno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_start', models.CharField(max_length=100)),
                ('batch_end', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='session_year_id',
        ),
        migrations.AddField(
            model_name='staff',
            name='subjects',
            field=models.ManyToManyField(related_name='staff_members', to='sms.subject'),
        ),
        migrations.AddField(
            model_name='student',
            name='batch_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='sms.batch'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendence',
            name='Session_Year_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sms.batch'),
        ),
        migrations.DeleteModel(
            name='Session_Year',
        ),
    ]
