# Generated by Django 5.1 on 2025-01-08 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0026_student_batch_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='batch_id',
        ),
    ]
