# Generated by Django 5.1 on 2025-01-09 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0028_student_batch_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='subjects',
        ),
        migrations.AddField(
            model_name='staff',
            name='subject_id',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.DO_NOTHING, to='sms.subject'),
            preserve_default=False,
        ),
    ]
