# Generated by Django 5.1 on 2025-01-09 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0029_remove_staff_subjects_staff_subject_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='subject_id',
        ),
    ]
