# Generated by Django 5.1 on 2025-01-11 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0032_remove_staff_subject_id_staff_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_notification',
            name='status',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
