# Generated by Django 5.1 on 2025-01-21 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0037_studentresult'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentresult',
            old_name='assignment_mark',
            new_name='internal_mark',
        ),
    ]
