# Generated by Django 5.1 on 2025-01-27 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0038_rename_assignment_mark_studentresult_internal_mark'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendence',
            old_name='Session_Year_id',
            new_name='batch_year_id',
        ),
    ]
