# Generated by Django 5.1 on 2025-01-27 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0039_rename_session_year_id_attendence_batch_year_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Attendence',
            new_name='Attendance',
        ),
        migrations.RenameModel(
            old_name='Attendence_Report',
            new_name='Attendance_Report',
        ),
    ]
