# Generated by Django 5.1 on 2025-01-28 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0041_rename_attendence_date_attendance_attendance_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance_report',
            name='attendance_id',
        ),
        migrations.RemoveField(
            model_name='attendance_report',
            name='student_id',
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='Attendance_Report',
        ),
    ]
